name: excel_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.1
  file_picker: ^4.3.0
  enough_convert: ^1.4.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  msix: ^2.8.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/

msix_config:
  display_name: ClubPetro Sorteios
  publisher_display_name: ClubPetro
  identity_name: ClubPetro.MySuite.ClubPetroSorteios
  msix_version: 1.0.0.0
  logo_path: C:\Users\Clubpetro-77\Documents\GitHub\excel_project\assets\images\launcher_icon.png
  capabilities: ""
